name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            cmake \
            ninja-build \
            libsqlite3-dev sqlite3 \
            bzip2 libbz2-dev \
            zlib1g-dev libssl-dev openssl \
            libgdbm-dev libgdbm-compat-dev liblzma-dev \
            libffi-dev uuid-dev libreadline-dev \
            libncurses5-dev libncursesw5-dev \
            zip unzip openjdk-17-jdk autoconf libtool pkg-config \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev
          pip install --upgrade pip buildozer "cython<3.0.0"


      - name: Build APK with Buildozer
        run: |
          rm -rf .buildozer
          sudo -u runner buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          
