- name: Build with Buildozer
  run: |
    buildozer -v android debug > build.log 2>&1 || true

- name: Upload build log
  uses: actions/upload-artifact@v4
  if: always() # Executa mesmo se a compilação falhar
  with:
    name: build-logs
    path: build.log
    
